databases:
  - name: haccp-trace-db
    databaseName: haccp_trace
    user: haccp_user
    plan: free

services:
  # Backend API Service
  - type: web
    name: haccp-trace-backend
    env: node
    plan: free
    buildCommand: |
      cd backend
      npm install
    startCommand: |
      cd backend
      npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: haccp-trace-db
          property: connectionString
      - key: CORS_ORIGIN
        fromService:
          name: haccp-trace-frontend
          type: web
          property: host
    healthCheckPath: /health
    autoDeploy: true
    branch: main

  # Frontend Static Site
  - type: web
    name: haccp-trace-frontend
    env: static
    plan: free
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: haccp-trace-backend
          type: web
          property: host
      - key: REACT_APP_ENVIRONMENT
        value: production
    autoDeploy: true
    branch: main
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: no-cache, no-store, must-revalidate 