services:
  - type: web
    name: haccp-trace-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: haccp-trace-db
          property: connectionString
      - key: CORS_ORIGIN
        fromService:
          name: haccp-trace-frontend
          type: web
          property: host
    healthCheckPath: /health
    autoDeploy: true
    branch: main 